/*
    Bindings module for the codegen (tier 2) reflection test. It includes the
    generated trampoline header (produced at build time into the binary dir) before
    calling reflect_, so the generated NB_REFLECT_TRAMPOLINE registrations are
    visible when reflect_class instantiates -- giving Worker a trampoline without a
    single line of hand-written trampoline code.
*/

// Note: this TU intentionally does NOT include any <nanobind/stl/*.h> caster
// headers. The std types used by the bound signatures (std::string, std::vector,
// std::map) get their casters from the generated header below, which the codegen
// emits automatically (roadmap #5).
#include <nanobind/nb_reflect.h>
#include <nanobind/trampoline.h>

#include "test_reflect_codegen.h"

// Generated by test_reflect_codegen_gen at build time (binary dir on the include
// path). Emits the required stl caster includes + any needed trampolines.
#include "test_reflect_codegen_tramp.gen.h"

namespace nb = nanobind;

NB_MODULE(test_reflect_codegen_ext, m) {
    nb::reflect_<^^reflect_codegen_test>(m);
}
