import pytest

try:
    import test_reflect_codegen_ext as t
    def needs_reflect(x):
        return x
except ImportError:
    needs_reflect = pytest.mark.skip(reason="C++26 reflection support required")


@needs_reflect
def test01_generated_trampoline_override():
    # Worker has no hand-written trampoline; the one used here was generated by
    # the reflection codegen step. A Python override of a pure virtual must be
    # dispatched into when C++ calls through a base reference.
    class MyWorker(t.Worker):
        def work(self, x):
            return x * 10

    w = MyWorker()
    assert w.work(3) == 30                 # direct Python call
    assert t.run_work(w, 3) == 30          # C++ -> Python override (generated trampoline)
    assert w.label() == 'worker'           # non-overridden -> C++ base
    assert t.run_label(w) == 'worker'      # C++ -> C++ base fallback


@needs_reflect
def test02_non_virtual_class_has_no_trampoline_issue():
    # Pod has no virtuals; the generator emitted no trampoline for it, and it
    # still binds normally.
    p = t.Pod()
    p.a = 5
    assert p.a == 5
