/*
    Bindings module for the codegen (tier 2) reflection test. It includes the
    generated trampoline header (produced at build time into the binary dir) before
    calling reflect_, so the generated NB_REFLECT_TRAMPOLINE registrations are
    visible when reflect_class instantiates -- giving Worker a trampoline without a
    single line of hand-written trampoline code.
*/

#include <nanobind/nb_reflect.h>
#include <nanobind/trampoline.h>
#include <nanobind/stl/string.h>

#include "test_reflect_codegen.h"

// Generated by test_reflect_codegen_gen at build time (binary dir on the include
// path). May be empty if nothing needed a trampoline.
#include "test_reflect_codegen_tramp.gen.h"

namespace nb = nanobind;

NB_MODULE(test_reflect_codegen_ext, m) {
    nb::reflect_<^^reflect_codegen_test>(m);
}
